### ISSUE TITLE
404 on http://purl.obolibrary.org/obo/imr.owl and http://purl.obolibrary.org/obo/iev.owl

### ISSUE THREAD

**Issue by tgbugs** [OBOFoundry/purl.obolibrary.org#353]
While doing NIFSTD cleanup I came across an old IMR_ identifier and went to figure out where it came from. This led to the discover of a resolver issue, so I did some digging.

http://www.ontobee.org/ontology/imr points to http://purl.obolibrary.org/obo/imr.owl which points to http://ontologies.berkeleybop.org/imr.owl (maintained by https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/imr.yml) which 404s.

I do not know the history behind this ontology so I don't know whether there is a reason it was removed, however it can be recovered.

The internet archive has a copy of the 2.24 version of the ontology available here https://web.archive.org/web/20131127090937/http://www.inoh.org/ontologies/MoleculeRoleOntology.obo (see also
https://web.archive.org/web/20130525055936/http://www.inoh.org/inohblog/main/ontologydata/).

I also found copies backed up with a note here http://download.baderlab.org/INOH/README.txt which pointed to this issue https://github.com/PathwayCommons/cpath2/issues/218.

Similar story for http://purl.obolibrary.org/obo/iev.owl as well, the difference being that the latest version doesn't seem to be on the archive, but can be found here http://download.baderlab.org/INOH/ontologies/EventOntology_172.obo.

@IgorRodchenkov

**Comment by cmungall** [comment]
The metadata we have is here:

http://obofoundry.org/ontology/imr.html

Even when an ontology is deprecated, we would like to have the purl pointing at the most recent version. Thanks for the archaeology.

Until relatively recently we were tracking the source file in the old cvs repo:

http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/genomic-proteomic/molecule_role.obo?view=log

but as you can see the most recent entries were just copying the HTML content of a 404

I went with the web archive URLs as the source for now (maybe should have used baderlab URLs, can change at any time). The builds to obocentral should happen within 24hrs, which is where the purls currently redirect.

I assume you need IMR for things like groupings of peptide hormones? Have you discussed this with PRO?

**Comment by tgbugs** [comment]
I haven't had a chance to review the exact content yet, but I don't think we were using that many classes from IMR. When I upgrade PRO from our current (very old) version I will also review IMR and see if there is anything to discuss.

**Comment by zhilianghu** [comment]
We recently encounter a similar issue on VT. The OBO Foundry PURL
http://purl.obolibrary.org/obo/vt.owl resolves to https://raw.githubusercontent.com/AnimalGenome/vertebrate-trait-ontology/master/current_release/vt.owl which has a versionIRI line:
<owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/vt/releases/2024-01-17/vt.owl"/> but the resource URL end up with a 404 (Not found) page (http://www.berkeleybop.org/ontologies/vt/releases/2024-01-17/vt.owl).

Not sure how this redirect works but we did use a github file structure to accommodate (https://github.com/AnimalGenome/vertebrate-trait-ontology ; see /releases/ folder). Any advice please what should be done at our end in order to comply with the requirement?

(Perhaps this is why OBO Foundry complains missing version IRI at https://dashboard.obofoundry.org/dashboard/vt/dashboard.html)

**Comment by jamesaoverton** [comment]
@zhilianghu I created a new issue here: https://github.com/OBOFoundry/purl.obolibrary.org/issues/972

**Comment by jamesaoverton** [comment]
This issue is ancient so I'm going to close it. If there's still work to be done, please create a new issue or reopen.
