### ISSUE TITLE
PURL for registry metadata

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/purl.obolibrary.org#427]
we make these available

https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/registry/ontologies.yml
https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/registry/ontologies.ttl

I'm getting increasing requests for these but this doesn't seem like a good URL to give out, I'd like to give out a PURL

What do we think of `http://purl.obolibrary.org/meta/` as the base URL? With fragments like ontologies.yml, ttl. We could also have void dumps in future.

If we agree I can look into making a PR on the code in this repo

**Comment by selewis** [comment]
Are the two mutually exclusive?

**Comment by alanruttenberg** [comment]
Maybe use ".well-known". https://tools.ietf.org/html/rfc5785
Concur with Suzi about ontology - not sure why one would then need a separate .ttl - have the contents effectively be instances in the ontology. Or, if the point it is rdf constructed according to some common recipe, then say so in the name, since an ontology can also be suffixed with .ttl

Re properties, FWIW I've used DOAP (https://github.com/ewilderj/doap/wiki)  in the past. 

1.1.  Appropriate Use of Well-Known URIs

   There are a number of possible ways that applications could use Well-
   known URIs.  However, in keeping with the Architecture of the World-
   Wide Web [W3C.REC-webarch-20041215], well-known URIs are not intended
   for general information retrieval or establishment of large URI
   namespaces on the Web.  Rather, they are designed to facilitate
   discovery of information on a site when it isn't practical to use
   other mechanisms; for example, when discovering policy that needs to
   be evaluated before a resource is accessed, or when using multiple
   round-trips is judged detrimental to performance.

   As such, the well-known URI space was created with the expectation
   that it will be used to make site-wide policy information and other
   metadata available directly (if sufficiently concise), or provide
   references to other URIs that provide such metadata.

**Comment by cmungall** [comment]
not totally sure I'm following.

A number of people rely on our metadata file. I believe most consume the yaml/json, some consume the .ttl. For the people consuming these, I would like to provide a PURL so they are not hardcoding github raw URLs in their applications.

Some choices are

 1. `http://purl.obolibrary.org/meta/registry.{yml,ttl,json}`
 2. `http://purl.obolibrary.org/obo/obo.{yml,ttl,json}`

(open to others)

The first is most straightforward. The second has the advantage of conceiving of the registry as one large ontology. As Suzi says not mutually exclusive but could be confusing to have two: unless the two served different purposes. Perhaps the use case for the first is people who want to be able to operate on the registry metadata and the second is for applications that want to import all of obo.

Don't see where well-known fits in.

**Comment by jamesaoverton** [comment]
I prefer a distinct registry resource (in multiple formats). `http://purl.obolibrary.org/meta/registry.{yml,ttl,json}` sounds good to me.

A single big OBO ontology would be cool, but raises a bunch of questions in my mind, and I don't think we're ready to take that plunge yet.

Since it won't change often, we can just hardcode this into https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/www/.htaccess or an `.htaccess` in a subdirectory.

**Comment by cmungall** [comment]
+1 for json-ld context too

just realized we have two files, the latter is not updated, ugh

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/registry/obo_context.jsonld
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/registry/context.jsonld

**Comment by zhengj2007** [comment]
I'd prefer a distinct registry resource using PURLs, http://purl.obolibrary.org/meta/registry.{yml,ttl,json,...}, same as @jamesaoverton

**Comment by jamesaoverton** [comment]
Do we have consensus on this, as implemented in PR #428?

**Comment by jamesaoverton** [comment]
We're planning to move forward with this, along the lines of #428. If you have a strong objection, let us hear your reasons now please.

**Comment by cmungall** [comment]
Doesn't seem to be working...

E.g.
http://purl.obolibrary.org/meta/ontologies.yml

just takes me to this gh repo

**Comment by jamesaoverton** [comment]
Fixed by #665
