### ISSUE TITLE
PURLs for APOLLO_SV

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#64]
I don't see this project in the registry, but PURL.org has entries for it. What to do? @alanruttenberg

**Comment by jamesaoverton** [comment]
Current term PURLs do not resolve properly. Compare: 

- http://purl.obolibrary.org/obo/APOLLO_SV_00000219
- http://www.ontobee.org/ontology/APOLLO_SV?iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000219

I think it's because the `/obo/apollo_sv/about/` entry is misconfigured on PURL.org.

**Comment by alanruttenberg** [comment]
Yes, the about entry is incorrect. It sets the ?iri= to http://purl.obolibrary.org/apollo_sv/ instead of http://purl.obolibrary.org/obo/

<pre>
id: /obo/apollo_sv/about/
type: partial
target: http://www.ontobee.org/browser/rdf.php?o=APOLLO_SV&iri=http://purl.obolibrary.org/apollo_sv/
maintainers: ALANRUTTENBERG,hoganwr,mbrochhausen,apollo_sv
status: Approved
</pre>

The entry for apollo_sv is in http://code.google.com/p/obo-registry/source/browse/trunk/metadata/ontologies.txt  

I'll create an entry for ontologies/ and commit it.

**Comment by alanruttenberg** [comment]
https://github.com/OBOFoundry/purl.obolibrary.org/pull/77

Please review before committing - first time creating one of these- and then close.

**Comment by jamesaoverton** [comment]
Closed by commit 116a98b40c607d543051679c3730e41d37351934
