### ISSUE TITLE
obo/SYMP does not resolve

### ISSUE THREAD

**Issue by psiotwo** [OBOFoundry/purl.obolibrary.org#838]
Getting 404 for http://purl.obolibrary.org/obo/symp.owl

**Comment by jamesaoverton** [comment]
The files were moved in this commit:

**Comment by tgbugs** [comment]
I'm still seeing issues with http://purl.obolibrary.org/obo/symp/releases/2022-04-05/symp.owl. It isn't 404ing perse, but for the past two weeks I have been hitting the `REDUCED_REDUNDANCY` page on http://ontologies.berkeleybop.org/ following redirects through

http://purl.oclc.org/obo/symp/releases/2022-04-05/symp.owl  
https://purl.oclc.org/obo/symp/releases/2022-04-05/symp.owl and  
http://www.berkeleybop.org/ontologies/symp/releases/2022-04-05/symp.owl  
which unfortunately seems to redirect to http://ontologies.berkeleybop.org.

This will break any scigraph load that imports the disease ontology.

**Comment by matentzn** [comment]
@tgbugs symp does not have version IRIs configured:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/symp.yml

I think this should be done, but you need to lobby the [SYMP developers](https://github.com/DiseaseOntology/SymptomOntology/issues) to do github releases, in order to create the tags required to set up a version IRI redirect config:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/aism.yml#L17


In any case, this needs a new issue, but IMO it should be on the SYMP issue tracker.

**Comment by tgbugs** [comment]
@matentzn good to know. I'll also hunt down how that version iri made it into the import chain as well since there is basically no way it could possibly resolve.
