### ISSUE TITLE
http://purl.obolibrary.org/obo take really long time to respond. 

### ISSUE THREAD

**Issue by Yueyang5566** [OBOFoundry/purl.obolibrary.org#978]
for example, http://purl.obolibrary.org/obo/DRON_00025623 take about 4 to 5 mins to respond. And I got time out error in my end.

**Comment by jamesaoverton** [comment]
Thank you for your report. I don't think this is a problem with the PURL system.

The role of the PURL system is to redirect our Permanent URLs to target web sites, so that the PURLs stay the same even if the targets change from time to time.

In this case the PURL system redirects <http://purl.obolibrary.org/obo/DRON_00025623> to the Ontobee ontology browser page at <https://ontobee.org/ontology/DRON?iri=http://purl.obolibrary.org/obo/DRON_00025623>. Other PURLs redirect to other ontology browsers, or to GitHub, etc.

As far as I can see, the PURL system is working properly, in a fraction of a second. If the page doesn't load properly, that's a problem with Ontobee, and should be reported to them at their mailing list at <https://groups.google.com/g/ontobee-discuss>.
